# Read the Nangate Library
read_liberty lib/NangateOpenCellLibrary_typical.lib

# Read the Netlist generated by Yosys
read_verilog outputs/priority_encoder_16to4_45nm.v

# Set the top module
link_design priority_encoder_16to4

# Read the constraints
read_sdc constraints/priority_encoder_16to4.sdc

# Check timing
report_checks -path_delay max -format full_clock_expanded
report_worst_slack -max
